

notifications:
  email:
    recipients:
      - humberto.a.sanchez.ii@gmail.com
    on_success: change # default: change
    on_failure: always # default: always

language: python

dist: noble

cache: pip

services:
  - xvfb

python:
  - "3.12"

install:
  - echo '***************************************************************'
  - uname -a
  - sudo apt update
  - sudo apt install libnotify-dev
  - sudo apt install libgtk-3-dev
  - sudo apt-get install -y -V libtiff-dev
  - sudo apt-get install -y  libsdl2-dev
  - echo '***************************************************************'
  - GLOBAL=`python --version`
  - echo $GLOBAL
  - PY_VERSION=${GLOBAL#* }
  - pyenv global ${PY_VERSION}
  - pip install --upgrade pip
  - pip install wheel
  - pip install setuptools
  - pip install twine
  - pip install build
  - pip install html-testRunner==1.2.1
  - pip install codeallybasic==1.30.0
  - pip install six==1.16.0
  - pip install attrdict3
  - URL=https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-24.04
  - pip install -U -f $URL wxPython

# command to run tests
script:
  - pip install buildlackey
  - unittests -v loud
